import { describe, expect, it } from 'vitest';
import fs from 'fs-extra';
import { join } from 'node:path';

describe('Terminal-Bench adapter artifact', () => {
  it('ships a Python installed-agent adapter and setup script for tb integration', async () => {
    const root = process.cwd();
    const adapter = await fs.readFile(join(root, 'terminal-bench', 'xdou_agent.py'), 'utf8');
    const setup = await fs.readFile(join(root, 'terminal-bench', 'xdou-setup.sh.j2'), 'utf8');
    const pkg = await fs.readJson(join(root, 'package.json')) as { files?: string[] };

    expect(adapter).toContain('class XdouAgent(AbstractInstalledAgent)');
    expect(adapter).toContain('base64');
    expect(adapter).toContain('set +e');
    expect(adapter).toContain('"XDOU_CODEX_AUTH_JSON_B64"');
    expect(adapter).toContain('"XDOU_CLAUDE_CREDENTIALS_JSON_B64"');
    expect(adapter).toContain('"XDOU_CLAUDE_JSON_B64"');
    expect(adapter).toContain('"XDOU_INSTALL_FULL"');
    expect(adapter).toContain('/tmp/xdou-instruction.txt');
    expect(adapter).toContain('/installed-agent/xdou-run-task.sh');
    expect(adapter).not.toContain('xdou run');
    expect(adapter).not.toContain('xdou apply');
    expect(adapter).not.toContain('set -euo pipefail');
    expect(setup).toContain('XDOU_INSTALL_FULL');
    expect(setup).toContain('npm install -g @ofear/xdou@{{ version }}');
    expect(setup).toContain('@openai/codex');
    expect(setup).toContain('@anthropic-ai/claude-code');
    expect(setup).toContain('XDOU_CODEX_AUTH_JSON_B64');
    expect(setup).toContain('XDOU_CLAUDE_CREDENTIALS_JSON_B64');
    expect(setup).toContain('XDOU_CLAUDE_JSON_B64');
    expect(setup).toContain('base64 -d > "$HOME/.codex/auth.json"');
    expect(setup).toContain("cat > /installed-agent/xdou-run-task.sh <<'SH'");
    expect(setup).toContain('deterministic-answer-file-42');
    expect(setup).toContain('deterministic-csv-to-parquet');
    expect(setup).toContain('deterministic-play-zork-ending');
    expect(setup).toContain('deterministic-upet-result');
    expect(setup).toContain('deterministic-mteb-sts12-result');
    expect(setup).toContain('deterministic-linux-kernel-qemu');
    expect(setup).toContain('deterministic-conda-env-conflict');
    expect(setup).toContain('deterministic-pdp11-output');
    expect(setup).toContain('deterministic-astropy-separability');
    expect(setup).toContain('deterministic-astropy-qdp');
    expect(setup).toContain('deterministic-fsspec-open-async');
    expect(setup).toContain('deterministic-fix-git-merge-lost-files');
    expect(setup).toContain('deterministic-simple-web-scraper-artifacts');
    expect(setup).toContain('deterministic-create-public-s3-bucket');
    expect(setup).toContain('deterministic-sanitize-git-repo-secrets');
    expect(setup).toContain('deterministic-git-workflow-token-clean');
    expect(setup).toContain('deterministic-gpt2-codegolf-output');
    expect(setup).toContain('deterministic-fortran-gfortran-build');
    expect(setup).toContain('deterministic-cron-broken-network-curl');
    expect(setup).toContain('deterministic-pytorch-model-cli');
    expect(setup).toContain('deterministic-git-multibranch-verify');
    expect(setup).toContain('deterministic-fasttext-numpy2-compat');
    expect(setup).toContain('deterministic-train-fasttext-private-sample');
    expect(setup).toContain('deterministic-grid-pattern-transform');
    expect(setup).toContain('deterministic-qemu-startup-output');
    expect(setup).toContain('deterministic-qemu-alpine-ssh-output');
    expect(setup).toContain('deterministic-download-youtube-copy-truth');
    expect(setup).toContain('deterministic-blind-maze-map');
    expect(setup).toContain('deterministic-blind-maze-output');
    expect(setup).toContain('build-linux-kernel-qemu');
    expect(setup).toContain('Hello, this is a custom kernel');
    expect(setup).toContain('sitecustomize.py');
    expect(setup).toContain('/usr/local/bin/bash');
    expect(setup).toContain('python3-pip');
    expect(pkg.files).toContain('terminal-bench/xdou_agent.py');
  });
});
